### ISSUE TITLE
当小球在飞行过程中连续点击屏幕会发生问题

### ISSUE THREAD

**Issue by LiuYuNan01** [KuoKuo666/CocosCreator-Bubble#1]
当小球在飞行过程中连续点击屏幕会发生问题

已修复 原因 在触摸结束的时候 是否射击小球 需要判断下    if (this.isShooting) return 如果在飞行过程中就return

 cc.director.on(EVENT.TOUCHEND_SHOOT, (data) => {
            console.log('BubbleMgr -on -touchend');
            // console.log(data);
            // 转为弧度
            if (this.isShooting) return
            let r = cc.misc.degreesToRadians(data);
            // 分量 x - sin  y - cos
            this.shootDir = cc.v2(-Math.sin(r), Math.cos(r));
            console.log(this.shootDir);
            // 开启射击
            this.isShooting = true;
        }, this);

楼主代码写的很不错  不会ts也能看懂。 分工明确

**Comment by KuoKuo666** [comment]
感谢勘误，稍后我会推上去。
